/* Auto-generated by build_html.mjs — do not edit by hand */
const CACHE_NAME = "goweb-manual-v1.0.1";
const PRECACHE_URLS = [
  "./",
  "./index.html",
  "./assets/fonts/mn-burger/MN Burge Bold Italic.otf",
  "./assets/fonts/mn-burger/MN Burge Bold.otf",
  "./assets/fonts/mn-burger/MN Burger Italic.otf",
  "./assets/fonts/mn-burger/MN Burger Light Italic.otf",
  "./assets/fonts/mn-burger/MN Burger Light.otf",
  "./assets/fonts/mn-burger/MN Burger.otf",
  "./images/01_login.png",
  "./images/02_dashboard.png",
  "./images/03_news_list.png",
  "./images/03b_action_menu.png",
  "./images/03c_bulk_actions.png",
  "./images/03d_delete_confirm.png",
  "./images/04_news_form.png",
  "./images/05_news_types.png",
  "./images/06_banners.png",
  "./images/07_gallery.png",
  "./images/08_calendar.png",
  "./images/09_pages.png",
  "./images/10_attractions.png",
  "./images/11_otop.png",
  "./images/12_promo_videos.png",
  "./images/13_box.png",
  "./images/14_editor_uploads.png",
  "./images/15_menu_top.png",
  "./images/16_menu_side.png",
  "./images/17_setting_intro.png",
  "./images/18_setting_org.png",
  "./images/19_setting_seo.png",
  "./images/20_eservice_services.png",
  "./images/21_eservice_complaints.png",
  "./images/22_eservice_summary.png",
  "./images/23_feedback.png",
  "./images/24_webboard.png",
  "./images/25_feedback_surveys.png",
  "./images/26_personal.png",
  "./images/27_ita.png",
  "./images/28_lpa.png",
  "./images/29_system_users.png",
  "./images/30_roles.png",
  "./images/31_permissions.png",
  "./images/32_logs.png",
  "./images/33_account.png",
  "./images/34_password.png"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;

      return fetch(request)
        .then((response) => {
          if (!response || response.status !== 200 || response.type === "opaque") {
            return response;
          }

          const responseClone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, responseClone));
          return response;
        })
        .catch(() => caches.match("./index.html"));
    })
  );
});
